language: node_js
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
  - redis-server
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - npm start
  - sleep 3
addons:
  hosts: derbyjs.com